from functions import *
alphabet = [
"a", 
"i",
"u",
"e",
"o",
"ka", 
"ki",
"ku",
"ke",
"ko",
"sa",
"shi",
"su",
"se",
"so",
"ta",
"ti",
"tsu",
"te",
"to",
"na",
"ni",
"nu",
"ne",
"no",
"ha",
"hi",
"he",
"hu",
"ho",
"ma",
"mi",
"mu",
"me",
"mo",
"ya",
"yu",
"yo",
"ra",
"ri",
"ru",
"re",
"ro",
"wa",
"n",
"wo",
"ga",
"gi",
"gu",
"ge",
"go",
"za",
"ji",
"zu",
"ze",
"zo",
"da",
"dzi",
"dzu",
"de",
"do",
"ba",
"bi",
"bu",
"be",
"bo",
"pa",
"pi",
"pu",
"pe",
"po"
] 

kana_functions = {
  "a" : [a_hir_turtle, a_kat_turtle], 
"i" : [i_hir_turtle, i_kat_turtle],
"u" : [u_hir_turtle, u_kat_turtle],
"e" : e_hir_turtle,
"o" : o_hir_turtle,
"ka" : ka_hir_turtle, 
"ki" : ki_hir_turtle,
"ku" : ku_hir_turtle,
"ke" : ke_hir_turtle,
"ko" : ko_hir_turtle,
"sa" : sa_hir_turtle,
"shi" : shi_hir_turtle,
"su" : su_hir_turtle,
"se" : se_hir_turtle,
"so" : so_hir_turtle,
"ta" : ta_hir_turtle,
"ti" : ti_hir_turtle,
"tsu" : tsu_hir_turtle,
"te" : te_hir_turtle,
"to" : to_hir_turtle,
"na" : na_hir_turtle,
"ni" : ni_hir_turtle,
"nu" : nu_hir_turtle,
"ne" : ne_hir_turtle,
"no" : no_hir_turtle,
"ha" : ha_hir_turtle,
"hi" : hi_hir_turtle,
"he" : he_hir_turtle,
"hu" : hu_hir_turtle,
"ho" : ho_hir_turtle,
"ma" : ma_hir_turtle,
"mi" : mi_hir_turtle,
"mu" : mu_hir_turtle,
"me" : me_hir_turtle,
"mo" : mo_hir_turtle,
"ya" : ya_hir_turtle,
"yu" : yu_hir_turtle,
"yo" : yo_hir_turtle,
"ra" : ra_hir_turtle,
"ri" : ri_hir_turtle,
"ru" : ru_hir_turtle,
"re" : re_hir_turtle,
"ro" : ro_hir_turtle,
"wa" : wa_hir_turtle,
"n" : n_hir_turtle,
"wo" : wo_hir_turtle,
"ga" : ga_hir_turtle,
"gi" : gi_hir_turtle,
"gu" : gu_hir_turtle,
"ge" : ge_hir_turtle,
"go" : go_hir_turtle,
"za" : za_hir_turtle,
"ji" : ji_hir_turtle,
"zu" : zu_hir_turtle,
"ze" : ze_hir_turtle,
"zo" : zo_hir_turtle,
"da" : da_hir_turtle,
"dzi" : dzi_hir_turtle,
"dzu" : dzu_hir_turtle,
"de" : de_hir_turtle,
"do" : do_hir_turtle,
"ba" : ba_hir_turtle,
"bi" : bi_hir_turtle,
"bu" : bu_hir_turtle,
"be" : be_hir_turtle,
"bo" : bo_hir_turtle,
"pa" : pa_hir_turtle,
"pi" : pi_hir_turtle,
"pu" : pu_hir_turtle,
"pe" : pe_hir_turtle,
"po" : po_hir_turtle
}